name: Run Tests and Generate Serenity Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_tests:
    name: Run Tests and Generate Serenity Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run Tests and Generate Serenity Report
        run: ./gradlew clean test aggregate

      - name: Upload Serenity Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: serenity-report
          path: build/reports/serenity