name: CI Serenity Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code_quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Run Code Quality Checks
        run: ./gradlew check

  build_test_and_serenity:
    name: Build, Test & Serenity Report
    runs-on: ubuntu-latest
    needs: code_quality
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Build and Run Tests
        run: ./gradlew clean test

      - name: Generate Serenity Report
        run: ./gradlew aggregate

      - name: Upload Serenity Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: serenity-report
          path: build/reports/serenity